name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.2.3
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write  # Allows the token to push changes, create releases, etc.

jobs:
  release:
    runs-on: windows-latest  # Use Windows for building the installer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      # Build the Windows CLI Binary
      - name: Build Windows Binary
        run: |
          mkdir -p bin
          go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.buildTime=$(Get-Date -UFormat '%Y-%m-%d_%H:%M:%S')" -o bin/gdcli.exe .

      - name: Verify Windows Binary Exists
        run: |
          if (-Not (Test-Path "bin/gdcli.exe")) { exit 1 }
          echo "gdcli.exe successfully built."

      # Install Inno Setup before building the installer
      - name: Install Inno Setup
        run: choco install -y innosetup

      - name: Build Windows Installer
        run: iscc setup.iss

      # Create GitHub Release and upload assets using softprops/action-gh-release
      - name: Create Release and Upload Assets
        id: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            bin/gdcli.exe
            gdcliSetup.exe
