name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.2.3
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write  # Allows the token to push changes, create releases, etc.

jobs:
  release:
    runs-on: windows-latest  # Use Windows for building the installer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      # Build the Windows CLI Binary
      - name: Build Windows Binary
        run: |
          mkdir -p bin
          go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.buildTime=$(Get-Date -UFormat '%Y-%m-%d_%H:%M:%S')" -o bin/gdcli.exe .

      - name: Verify Windows Binary Exists
        run: |
          if (-Not (Test-Path "bin/gdcli.exe")) { exit 1 }
          echo "gdcli.exe successfully built."

      # Install Inno Setup before building the installer
      - name: Install Inno Setup
        run: choco install -y innosetup

      - name: Build Windows Installer
        run: iscc setup.iss

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Store upload URL
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $env:GITHUB_ENV

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./bin/gdcli.exe
          asset_name: gdcli.exe
          asset_content_type: application/octet-stream

      # Upload Windows Installer
      - name: Upload Windows Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./gdcliSetup.exe
          asset_name: gdcliSetup.exe
          asset_content_type: application/octet-stream
